services:
    app.form.type.todo:
        class: AppBundle\Form\TodoType
        arguments: ['@app.form_field.provider']
        tags:
            - { name: form.type }

    app.form_field.provider:
        class: 'AppBundle\Services\FormProvider'
        arguments: ['@form.factory']

    app.add_description_field:
        class: 'AppBundle\Services\DescriptionFieldProvider'
        tags:
            - { name: 'form.field_provider'}
    app.add_date_field:
        class: 'AppBundle\Services\DateFieldProvider'
        tags:
            - { name: 'form.field_provider'}